import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import type { XWikiClient } from '../client.js';

export function register(server: McpServer, client: XWikiClient): void {
  server.tool(
    'export_page',
    `Export a wiki page as a PDF file. Returns the PDF as base64-encoded content along with size and content type.

The PDF is generated by xWiki's built-in export engine and includes rendered content, styles, and images.

Note: PDF export requires the PDF export extension to be installed on the xWiki instance.`,
    {
      space: z.string().describe("Wiki space name (e.g. 'Main', 'Sandbox')"),
      page: z.string().describe("Page name (e.g. 'WebHome')"),
    },
    async ({ space, page }) => {
      const result = await client.exportPage(space, page);
      return {
        content: [{
          type: 'text',
          text: JSON.stringify({
            space: result.space,
            page: result.page,
            format: result.format,
            content_type: result.content_type,
            size_bytes: result.size_bytes,
            size_kb: Math.round(result.size_bytes / 1024),
            content_base64: result.content_base64,
          }, null, 2),
        }],
      };
    },
  );
}
